version: '3.8'

services:
    db: 
        image: postgres
        container_name: database_mfs
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=tutilabs
            - POSTGRES_PASSWORD=tutimfs
            - POSTGRES_DB=user_mfs
        volumes:
            - pgdata:/data/postgres
        
volumes:
    pgdata:
        driver: local